pipeline:
  build_linux_amd64:
    image: golang:1.10
    group: build
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - make build
  docker:
    image: plugins/docker
    username: docker-user
    password: docker-name
    repo: rozendhyan/golang-http
    tags: lastest
    #secrets: [ rozendhyan, rozen0612 ]
    dockerfile: dockerfile
    default_tags: true
    when:
      event: [ push, tag ]